# Generated by Django 3.2.6 on 2025-03-18 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historia_clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_evento', models.CharField(choices=[('Examen Medico', 'Examen Medico'), ('Consulta', 'Consulta'), ('Preescripcion', 'Preescripcion'), ('Cirugia', 'Cirugia')], max_length=50)),
                ('fecha_y_hora_del_evento', models.DateTimeField()),
                ('especificaciones', models.TextField(blank=True, null=True)),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_medicos', to='historia_clinica.historiaclinica')),
            ],
        ),
    ]
