# Generated by Django 3.2.6 on 2025-03-14 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Historiales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='condicionesMedicas',
            new_name='condiciones_medicas',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='tipoSangre',
            new_name='tipo_de_sangre',
        ),
    ]
