# Generated by Django 3.2.6 on 2025-03-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiales', '0002_auto_20250313_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cirugias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cirugia', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_consulta', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(max_length=80)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('fecha_y_hora_evento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Preescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_medicamento', models.CharField(max_length=100)),
                ('fecha_y_hora_evento', models.CharField(max_length=100)),
            ],
        ),
    ]
