# Generated by Django 3.2.6 on 2025-03-14 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Historiales', '0003_cirugias_consultas_examenmedico_preescripcion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cirugias',
            new_name='Cirugia',
        ),
        migrations.RenameModel(
            old_name='Consultas',
            new_name='Consulta',
        ),
    ]
